env:
    sumo_config: "../sumo/simple.sumocfg"
    vehicle_list:
        ego:
            position: 100
            depart_time: 0
            lane: 1
            route_id: r_0
        v1:
            position: 120
            depart_time: 0
            lane: 1
            route_id: r_0
