env:
    sumo_config: sumo/simple.sumocfg
    speed_limit: 30
    vehicle_speed_mean: 25
    vehicle_speed_variation: 2
    num_random_vehicles: 20
    vehicle_time_gap: 2.0
    goal:
        x: 800
    reward:
        goal_bonus: 0
        off_lane_penalty_factor: 1
        speed_penalty_factor: 0
        acceleration_penalty_factor: 0
        lateral_speed_penalty_factor: 0
        alive_bonus: 8
        safety_penalty: 0

alg:
    name: cmdp
    gamma: 0.99
    update_freq: 100
    batch_size: 1024
    lr: 0.0001
    actor_lr: 0.01
    alpha: 1
    actor_threshold: 0.5
    network_width: 256

