env:
    sumo_config: sumo/simple.sumocfg
    speed_limit: 30
    vehicle_speed_mean: 25
    vehicle_speed_variation: 2
    num_random_vehicles: 20
    vehicle_time_gap: 2.0
    goal:
        x: 800
    reward:
        goal_bonus: 0
        off_lane_penalty_factor: 1
        speed_penalty_factor: 1
        acceleration_penalty_factor: 1
        lateral_speed_penalty_factor: 3
        alive_bonus: 8
        safety_penalty: 0
alg:
    name: safe_ddqn
    action_x_acc: 2
    action_y_acc: 1
    gamma: 0.99
    epsilon_start: 1.0
    epsilon_end: 0.05
    epsilon_decay: 100000
    update_freq: 128
    batch_size: 4096
    network_width: 256
    memory_size: 200000
    optimizer: adam
    weight_decay: 0.01
    lr: 0.00001
    lambda_learning_rate: 1
    lambda_update_start_episode: 64
    lambda_update_freq: 16
    safety:
        near_crash:
            lambda: 100
            threshold: 0.05
        crash:
            lambda: 100
            threshold: 0.001
        near_off_road:
            lambda: 100
            threshold: 0.1
        off_road:
            lambda: 100
            threshold: 0.001