env:
    sumo_config: sumo/simple.sumocfg
    speed_limit: 30
    vehicle_speed_mean: 25
    vehicle_speed_variation: 2
    num_random_vehicles: 20
    goal:
        x: 1000
    reward:
        goal_bonus: 0
        crash_penalty: -100
        off_road_penalty: -10
        off_lane_penalty_factor: 1
        speed_penalty_factor: 1
        acceleration_penalty_factor: 1
        alive_bonus: 10
        safety_penalty: 10
